name: assemble
on:
  workflow_dispatch:
    branches:
      - master
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'
jobs:
  cargo-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: cargo test

  link-dynamically:
    needs: cargo-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - run: cargo build --release
      - run: |
          ls -alh target/release
          file target/release/renga-service

  link-statically:
    needs: cargo-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-musl

      - run: sudo apt install musl-tools -y

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-musl-${{ hashFiles('**/Cargo.lock') }}

      - run: |
          cargo build \
            --target=x86_64-unknown-linux-musl \
            --release
      - run: |
          ls -alh target/x86_64-unknown-linux-musl/release
          file target/x86_64-unknown-linux-musl/release/renga-service
